import { ScholarshipApplication, Student } from "@/types";

export const initialStudents: Student[] = [
  {
    id: "STUDENT_001",
    name: "Priya Sharma",
    category: "OBC",
    stateOfDomicile: "Rajasthan",
    institutionName: "Govt. Degree College, Alwar",
    courseName: "B.Sc. Mathematics (Year 2)",
    rollNumber: "ALW-2023-BSC-089",
    maskedAadhaar: "XXXX-XXXX-4819",
    maskedBankAccount: "SBI - XXXX8912",
  },
  {
    id: "STUDENT_002",
    name: "Amit Verma",
    category: "SC",
    stateOfDomicile: "Uttar Pradesh",
    institutionName: "Kashi Naresh Govt. PG College, Gyanpur",
    courseName: "B.Com (Year 2)",
    rollNumber: "KN-2023-BCOM-142",
    maskedAadhaar: "XXXX-XXXX-9120",
    maskedBankAccount: "PNB - XXXX4190",
  },
];

export const initialApplications: ScholarshipApplication[] = [
  {
    id: "RJ202425008912",
    studentId: "STUDENT_001",
    student: initialStudents[0],
    schemeName: "Post-Matric Scholarship Scheme for OBC Students (Higher Education)",
    academicYear: "2024-2025",
    submissionDate: "2024-10-12T10:30:00Z",
    lastUpdated: "2024-10-18T14:15:00Z",
    currentState: "DEFECTIVE_INSTITUTE",
    currentDesk: "COLLEGE_INO",
    daysAtCurrentDesk: 6,
    slaMaxDays: 15,
    defects: [
      {
        id: "DEF_001",
        documentId: "DOC_BONAFIDE_001",
        documentType: "BONAFIDE_CERTIFICATE",
        officialCode: "INO_REJ_SEAL_MISSING",
        officialReason: "Institution Seal / Principal Signature Missing",
        plainExplanation: "Your college clerk noted that the uploaded Bonafide Certificate does not have the official round stamp of the Principal.",
        correctionInstructions: "Get the Bonafide stamped by the College Admin Office and re-upload.",
        isResolved: false,
        flaggedAt: "2024-10-18T14:15:00Z",
      },
    ],
    documents: [
      {
        id: "DOC_BONAFIDE_001",
        applicationId: "RJ202425008912",
        type: "BONAFIDE_CERTIFICATE",
        fileName: "Priya_Bonafide_Unstamped.pdf",
        fileUrl: "/synthetic/bonafide_defective.png",
        uploadDate: "2024-10-12T10:30:00Z",
        isDefective: true,
      },
      {
        id: "DOC_INCOME_001",
        applicationId: "RJ202425008912",
        type: "INCOME_CERTIFICATE",
        fileName: "Income_Cert_2024_Priya.pdf",
        fileUrl: "/synthetic/income_valid.png",
        uploadDate: "2024-10-12T10:30:00Z",
        isDefective: false,
      },
    ],
    timeline: [
      {
        id: "TL_01",
        state: "SUBMITTED",
        desk: "COLLEGE_INO",
        title: "Application Submitted Online",
        description: "Application successfully registered on portal by student.",
        timestamp: "2024-10-12T10:30:00Z",
        isCompleted: true,
      },
      {
        id: "TL_02",
        state: "DEFECTIVE_INSTITUTE",
        desk: "COLLEGE_INO",
        title: "Defect Flagged by College Nodal Officer",
        description: "Marked defective: Principal round stamp missing on Bonafide Certificate.",
        timestamp: "2024-10-18T14:15:00Z",
        isCompleted: true,
      },
      {
        id: "TL_03",
        state: "DISTRICT_VERIFICATION",
        desk: "DISTRICT_DNO",
        title: "District Welfare Officer Verification",
        description: "Community quota, domicile and scheme budget validation.",
        timestamp: null,
        isCompleted: false,
      },
      {
        id: "TL_04",
        state: "DISBURSED",
        desk: "PFMS_DBT",
        title: "Direct Benefit Transfer (DBT) Payment",
        description: "Payment credit via Aadhaar Payment Bridge to bank account.",
        timestamp: null,
        isCompleted: false,
      },
    ],
  },
  {
    id: "UP202425091844",
    studentId: "STUDENT_002",
    student: initialStudents[1],
    schemeName: "Post-Matric Scholarship Scheme for SC Students",
    academicYear: "2024-2025",
    submissionDate: "2024-09-10T09:00:00Z",
    lastUpdated: "2024-11-20T16:45:00Z",
    currentState: "DISBURSED",
    currentDesk: "COMPLETED",
    daysAtCurrentDesk: 0,
    slaMaxDays: 15,
    defects: [],
    documents: [
      {
        id: "DOC_BONAFIDE_002",
        applicationId: "UP202425091844",
        type: "BONAFIDE_CERTIFICATE",
        fileName: "Amit_Bonafide_Stamped.pdf",
        fileUrl: "/synthetic/bonafide_valid.png",
        uploadDate: "2024-09-10T09:00:00Z",
        isDefective: false,
      },
    ],
    timeline: [
      {
        id: "TL_11",
        state: "SUBMITTED",
        desk: "COLLEGE_INO",
        title: "Application Submitted",
        description: "Application registered by student.",
        timestamp: "2024-09-10T09:00:00Z",
        isCompleted: true,
      },
      {
        id: "TL_12",
        state: "INSTITUTE_VERIFICATION",
        desk: "COLLEGE_INO",
        title: "College Verified",
        description: "Approved by Institute Nodal Officer.",
        timestamp: "2024-09-25T11:20:00Z",
        isCompleted: true,
      },
      {
        id: "TL_13",
        state: "DISTRICT_VERIFICATION",
        desk: "DISTRICT_DNO",
        title: "District Approved",
        description: "Approved by District Welfare Officer.",
        timestamp: "2024-10-15T15:10:00Z",
        isCompleted: true,
      },
      {
        id: "TL_14",
        state: "DISBURSED",
        desk: "PFMS_DBT",
        title: "₹24,500 Credited via DBT (UTR: SBIN0089123498)",
        description: "Payment credited to PNB Account ending in 4190.",
        timestamp: "2024-11-20T16:45:00Z",
        isCompleted: true,
      },
    ],
  },
];
